services:
  mongo-dev:
    image: mongo:latest
    restart: always
    environment:
     - MONGO_INITDB_ROOT_USERNAME=sally
     - MONGO_INITDB_ROOT_PASSWORD=sally
     - MONGO_INITDB_DATABASE=sally
    ports:
      - 27017:27017
    volumes:
      - banco-data:/data/db

volumes:
  banco-data: